# Generated by Django 3.2.3 on 2021-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=20),
        ),
    ]
